### ISSUE TITLE
susy-breakpoint and vertical rhythm - doesn't update?

### ISSUE THREAD

**Issue by tbredin** [ericam/susy#345]
I think I've found an issue with the debug baseline grids output by the susy breakpoint mixin, which doesn't seem to update my vertical rhythm when it's adjusted between breakpoints. 

I'm using the following compass mixins in conjunction with susy 2 & breakpoint to control my vertical rhythm:

```SCSS
$large-width: 768px;
$large-layout: 14 (52px 32px);

$mobile-type-scale: 0.75;

// setting up vertical rhythm
html {
    $base-font-size: 16px * $mobile-type-scale;
    $base-line-height: 22px * $mobile-type-scale;
    @include establish-baseline($base-line-height);

    @include susy-breakpoint($large-width, $large-layout) {
        $base-font-size: 16px;
        $base-line-height: 22px;
        @include establish-baseline($base-line-height);
    }
}

// example tag
$h1-size: 48px;

h1 {
    @include adjust-font-size-to($h1-size * $mobile-type-scale);
    @include rhythm(0, 1, 1, 0, $h1-size * $mobile-type-scale);

    @include susy-breakpoint($large-width, $large-layout) {
        @include adjust-font-size-to($h1-size);
        @include rhythm(0, 1, 1, 0, $h1-size);
    }
}
```

Now I'm quite new to Susy (2, that is) and haven't attacked baseline grids in this much detail before - and this seems quite long winded to me - but I can't get the baseline grid to update at different breakpoints.

One alternative I've tried has been to just scale the type based on the body font size (probably a cleaner way), but that doesn't seem like a method that will get me get me any kind of useful debug output... right?

Is this broken or am I just approaching this poorly?
