### ISSUE TITLE
What happened with gutter function/mixin in Susy 2?

### ISSUE THREAD

**Issue by Lamp27** [ericam/susy#424]
This's my susy config
```scss
    $susy: (
        flow: ltr,
        math: fluid,
        output: float,
        gutter-position: right,
        container: 1000px,
        container-position: center,
        columns: 12,
        gutters: .15,
        column-width: false,
        global-box-sizing: content-box,
        last-flow: to,
        debug: (
                image: show,
                color: rgba(#66f, .25),
                output: overlay,
                toggle: top right,
        ),
        use-custom: (
                background-image: true,
                background-options: false,
                box-sizing: true,
                clearfix: false,
                rem: true,
        )
    );
```
Test code:
```scss
    .test {
        @include gutter();
        margin-bottom: gutters();
    }
```
After compiling they'r return nothing...

Or
```scss
    .test {
          margin-left: span(2) + gutters(2);
    }
```
After compile, displays an error: **Invalid null operation: "15.75092% plus null"**

What's the problem? It's looks like a bug.
