### ISSUE TITLE
Add "at-width" syntax to gutters

### ISSUE THREAD

**Issue by jakob-e** [ericam/susy#447]
First let me state I'm very new to susy – so bear with my ignorance. 

To ease the job of creating fluid grids from pixel based designs implementing a base-width would be very helpful. The base width does not restrict the grid in any ways – it only helps to establish a "design-at-100%" state to allow you to set gutters in pixels (could also be used to calculate pixel based columns in a fluid grid).  

Here is my first sketchy take on how to: 
http://sassmeister.com/gist/594f63442901485c8ed6
or http://codepen.io/jakob-e/pen/YPJKpv

I'm thinking something like this – not as a wrapper but working from the belly of susy.
````SCSS

// Gutter ratio calculation 
// Note! this is a first draft why the math could need some love
// and why I may have missed cases where this would be bad.  

@function gutter-ratio(
  $grid-map,
  $silent: false
  ){
  $base-width: _susy-deep-get($grid-map, base-width);
  @if not $base-width { 
    // We did not set a base-width
    @return $map; 
  }
  
  // Merge grid map and defaults
  $map: _susy-deep-merge($susy-defaults, $grid-map);
  
  $gutters : susy-get(gutters, $map); 

  // Make silent gutter validation
  @if valid-gutters($gutters, true){
    // Gutters are not invalid (unitless)
    @return $map;
  }
  $columns: susy-get(columns, $map); 
  $position: susy-get(gutter-position, $map); 
  $spread: if(is-split($position),0,-1);
  
  // TODO – Add unit conversion between base-width and gutters
  
  $total-gutter-width: $gutters * ($columns + $spread);
  // Gutter size causes span to become negative or NaN%        
  @if $base-width / $columns <= $total-gutter-width / ($columns + $spread) and not($silent) {
  	$warn: 'Gutters must be less than: #{$total-gutter-width / ($columns + $spread)}';
  	@warn $warn ; 
  }
  
  $total-span-width: $base-width - $gutters * ($columns + $spread);
  $ratio: $total-gutter-width / ($columns + $spread) / $total-span-width * $columns;
  
  // Add calculated gutter ratio
  @return map-merge($map, (gutters: $ratio));
}



// ---------------------------
// Config
//
$base-width: 1180px;  // Design width matching e.g a photoshop file
$max-width : 1400px;  // Maximum grid width   
$gutter-width: 40px;  // Gutter width according to design

// When creating the grid set the max-width to
// equal the base-width (design width).   
$max-width: $base-width;



// ---------------------------
// Gutter position: after
//
$grid-one: (
  columns: 12,
  base-width: $base-width,
  gutters: $gutter-width,
);

// ---------------------------
// Gutter position: split
//
$grid-two: (
  columns: 12,
  base-width: $base-width,
  gutters: $gutter-width,
  gutter-position: split
  
);

// ---------------------------
// Calculate the gutter ratio
//
$grid-one: gutter-ratio($grid-one, true);
$grid-two: gutter-ratio($grid-two, true);

````
