### ISSUE TITLE
Superfish hidden by susy

### ISSUE THREAD

**Issue by webmasterpf** [ericam/susy#456]
Hi

I'm using Susy 2 to make a drupal 6 custom theme but my superfish menu sub item list his hidden by the overflow of the container..
you can see the fact here : http://d6sbx1.pfdev.tk/

do you know about a fix ? is it a wrong coding by myself ?

thanks

**Comment by ericam** [comment]
Susy doesn't apply the overflow property anywhere. Looks like you've added it to `#header .headBas`

**Comment by webmasterpf** [comment]
I go to see that.How can i skip the clearfix depending the breakpoint ?

**Comment by ericam** [comment]
The `container` mixin applies 4 things, which you could apply separately, if you want some parts without others.

```scss
.container {
  @include susy-clearfix; // use susy-clearfix if you want a simple clearfix
  @include show-grid(); // show the grid-debug background image or overlay
  max-width: container(); // use the container function to set width
  margin: 0 auto; // use margins for centering
}
```
