### ISSUE TITLE
Performance improvements needed: span mixin

### ISSUE THREAD

**Issue by DenisMir** [ericam/susy#465]
The `span` mixin eats up all the compilation performance. This problem got even more obvious after having switched to libsass. When dropping all the `@include span` calls I'm down at a 10-100ms (depending on the machine) but adding the span calls the compile time adds up to over 2 seconds. I don't know if it is even possible to improve the susy performance in this area but it would be a big improvement. At the moment this single mixin makes up 90% of the sass compile time.

I don't know if it helps but this is the current grid setup: 

```scss
$grid: (columns: 12, column-width: false, gutters: 1 / 1.618, gutter-position: after, math: fluid);
@include layout($grid);

.col__b0-full {
  @include span(full);
}
... (and a lot more grid classes)
```
