### ISSUE TITLE
Infinite loop when $susy-media contains key=value map

### ISSUE THREAD

**Issue by mikemonteith** [ericam/susy#485]
```scss
$susy-media: (
  print: 'print'
);

@import susy-media(print){
  img{
    display:none;
  }
}
```

This results in an infinite loop error.
