### ISSUE TITLE
Add a grid flag inside of $susy - here's a temporary fix

### ISSUE THREAD

**Issue by isarmstrong** [ericam/susy#490]
When I'm designing, I often want to flag all of my grids on and off at the same time. It seems like there should be a quick option (grids: on | color: $color | rotatecolors: true) in the $susy variable.

For the time being, I accomplished it like this, where the $grids variable flags all of the displays.

```css
// SUSY Grid Setup
$grids: 'off';
$susy: (
  columns: 4,
  gutters: 1/16,
  math: fluid,
  output: float,
  gutter-position: split
);
$show: null;
@if $grids == 'on' { $show: 'show'; }
```

And then in the actual definitions below:

```css
.magic {
	overflow: hidden;
	padding: 4rem 0;
	h1,h2 {
		font-family: $simplifica;
		font-size: 2.5rem;
		line-height: 3.2rem;
		color: $graphite-dark;
	}
	.main-content {
		@include span(4 of 4);
		@include breakpoint($tab) {
			@include span(6 of 6);
		}
		@include breakpoint($desk) {
			@include span(8 of 12);
		}
		@include breakpoint($hd) {
			@include span(10 of 15);
		}
	}
	p {
		color: $graphite-dark;
		text-align: justify;
	}
	@include container($show);
	@include breakpoint($micro) {
    @include with-layout(98% 2) { // default is set to 6-columns
      @include container($show);
    } // default is returned to global setting
  }
	@include breakpoint($tab) {
    @include with-layout(97% 6) { // default is set to 6-columns
      @include container($show);
    } // default is returned to global setting
  }
	@include breakpoint($desk) {
    @include with-layout(95% 12) { // default is set to 8-columns
      @include container($show);
    } // default is returned to global setting
  }
	@include breakpoint($hd) {
    @include with-layout(66rem 15) { // default is set to 8-columns
      @include container($show);
    } // default is returned to global setting
  }
}
```
