### ISSUE TITLE
Going from split to after gutter position between breakspoints may not be correctly handled

### ISSUE THREAD

**Issue by ctumolosus** [ericam/susy#497]
If you [view the output of the code below](http://sassmeister.com/gist/74aaf5b64e6bede593a0), you will notice that, on my desktop breakpoint, the `margin-left` applied during `gutter-position: split` will be inherited by the selectors after switching to `gutter-position: after`. I'm not certain whether I'm using Susy correctly,  but I would expect the `margin-left` to be reset to `0` automatically.

```scss
@import "breakpoint";
@import "susy";

$layout-mobile: layout(4 20/60 fluid float split);
$layout-desktop: layout(12 (67px 20px) 1024px fluid float after);

@include layout($layout-mobile);

.container {
  @include container;
}

.left {
  @include span(2);
}

.right {
  @include span(2)
}

@include susy-breakpoint('1024', $layout-desktop) {
  
  .container {
    @include container;
  }
  
  .left {
    /* where is my margin-left reset? */
    @include span(6);
  }
  
  .right {
    /* where is my margin-left reset? */
    @include span(6 last);
  }
}
```
