### ISSUE TITLE
No margin-right in last

### ISSUE THREAD

**Issue by gagaga67** [ericam/susy#507]
Hello!
Doesn't work added margin-right:0 in mixin last. Only float: right. Susy 2.2.5.

**Comment by ericam** [comment]
I'm not sure I understand the question or issue. Can you show me what you input, what you expected, and what you are seeing instead?

**Comment by gagaga67** [comment]
Html:
<div class="page">
<section class="content"></section>
<aside class="sidebar"></aside>
</div>

Scss:
.page {
@include container(1280px);
}
.content{
  @include span(10 of 16);
  ...
}
.sidebar{
  @include span(6 of 16);
// or @include span(6 of 16 last);
  @include last;
}

CSS:
.content {
    float: left;
    margin: 0.5em 0.625%;
    width: 61.25%;
}
.sidebar {
    float: right;
    margin: 0.5em 0.625%; // right margin not 0 with mixin last, is not true?
    width: 36.25%;
}

**Comment by ericam** [comment]
There's no way that Susy would give the shorthand `margin: 0.5em 0.625%;` output, so that must be coming from somewhere else? When you use the `last()` mixin, it should override the right margin, but you will see both in the output. See [this demo on sassmeister](http://sassmeister.com/gist/62011257ca577f844c8d). 

```scss
.content {
  width: 62.02532%;
  float: left;
  margin-right: 1.26582%;
}

.sidebar {
  // from span mixin:
  width: 36.70886%;
  float: left;
  margin-right: 1.26582%;
  // from last mixin:
  float: right;
  margin-right: 0; 
}
```
