### ISSUE TITLE
Planning for Susy v3

### ISSUE THREAD

**Issue by ericam** [ericam/susy#519]
# Philosophy
The goal of Susy v3 is to separate the math layer from the css-output layer. At the core, Susy is a grid calculator that can be used for any CSS layout technique. That simplicity and flexibility is too easily overshadowed by attempts to provide every common shortcut. By reducing the core to functions, Susy can truly shine as a grid-system system, and the shortcuts can be provided in a more modular ecosystem of plugins designed to handle specific needs.

## 1. The Core
The core will focus on two functions and five global settings — only what is necessary for describing grid math, but nothing to do with actual CSS output. Developers can use the core to create their own grid-systems on the fly.

```scss
$susy: (
  'columns': 12,
  'gutters': 1/4,
  'column-width': null, // optional width for static math
  'math': 'fluid' or 'static',
  'spread': 'narrow' or 'wide' or 'wider',
);

.functions {
  width: span(1 of 4);
  margin-right: gutter(of 4);
}
```

## 2. Plugins
Plugins can be created to provide common shortcuts for different CSS layout techniques (float, isolation, flex-box, inline-block, table-cell, gutters before or after or inside, etc.) — as well as different pre-built systems (oocss, 960gs, etc).

```scss
@mixin susy-float ( // names are obviously not final...
  $span,
  $flow: ltr
) {
  float: if($flow == ltr, left, right);
  width: span($span);
  margin-right: gutter();
}

@mixin susy-flex (
  $span
) {
  flex: 1 0 span($span);
  padding-left: gutter()/2;
  padding-right: gutter()/2;
}
```

## 3. Tutorials
It will be important to provide lots of examples on how to create your own grid system using the Susy core engine.
