### ISSUE TITLE
Setting gallery with pixel-based width and pixel-based gutter

### ISSUE THREAD

**Issue by patrickbjohnson** [ericam/susy#520]
I'm unable to find a way to create a gallery grid with a fixed width and column, but scales as well. Here's a paired down test: http://sassmeister.com/gist/99ff4cce02003941b783

Not sure if I'm doing something incorrectly? I want the max-width of each `portfolio-item` should be `360px` with a `30px` gutter.

**Comment by ericam** [comment]
I believe you want [something like this](http://sassmeister.com/gist/1b92d9057531cddcb8c9)?

**Comment by patrickbjohnson** [comment]
This would be it! Didn't know I'd need to establish a `$susy` map to set up specific column widths. 

Will doing this here effect any other reference to `@include gallery()` before or after these lines of code in my CSS?

**Comment by ericam** [comment]
Well, that setting really only affects the container - where we set `max-width`. But yes, anything you change in the global `$susy` map will affect everything. You can also create your own alternative settings maps and pass them in wherever you want:

```scss
$this-gallery: (
  columns: 3,
  gutters: 30px/360px,
  column-width: 360px,
);

.body {
  @include container($this-gallery);
}

.portfolio-item{
  @include gallery(1 of $this-gallery);
}
```
