### ISSUE TITLE
Using span mixin in @media results in box-sizing without value

### ISSUE THREAD

**Issue by hashworks** [ericam/susy#522]
Example:
```scss
.foobar-test {
    @media(max-width: 780px) {
        @include span(first to 12);
    }
}
```

Results in:
```css
@media  (max-width: 780px) {
  .foobar-test {
    -webkit-box-sizing: ;
    -moz-box-sizing: ;
    box-sizing: ;
    width: 100%;
    [...]
  }
}
```
