### ISSUE TITLE
Add susy-nested() function to v3 API

### ISSUE THREAD

**Issue by ericam** [ericam/susy#525]
The function is useless for symmetrical grids, but you can't live without it in an asymmetrical world. Seems maybe worth adding to the core (since the core does support an asymmetrical approach) — with warnings if you try to use it in a symmetrical context. We already have a simple version of it in our AG tests:

```scss
@function nested (
  $span,
  $config: ()
) {
  $data: map-merge($config, susy-span-parser($span));
  $data: susy-settings($data);

  $span: map-get($data, 'span');
  $location: map-get($data, 'location');
  $columns: map-get($data, 'columns');

  @return su-slice($span, $location, $columns);
}
```
