### ISSUE TITLE
Debug color

### ISSUE THREAD

**Issue by mig-25** [ericam/susy#527]
As context is crucial in susy, In the debugging section of the map, I wonder if it would be possible to have the grid color change for different context on the page. So it would be easy to see what divs belong to its closest context upwards.

-Cheers

**Comment by ericam** [comment]
Susy isn't actually aware of your different contexts unless you tell it explicitly. But you can do that yourself, wherever you are already defining the new grid context. If you are passing in a map for each context, add your desired debug color to the map:

```scss
$large: (
  'columns': 12,
  'debug': ('color': red),
);

@include susy-breakpoint($my-breakpoint, $large) {
  @inlcude show-grid();
}
```

If you are using the shorthand syntax, you'll need to pass in a map for that one setting (you can store this in a variable for readability:



```scss
$large-grid-color: ('debug': ('color': red));

@include susy-breakpoint($my-breakpoint, 12 $large-grid-color) {
  @inlcude show-grid();
}
```
